version: '3.8'

services:
  # 1. Dịch vụ Backend (Chạy ở cổng 8000)
  backend:
    build: ./backend
    container_name: todo_backend
    ports:
      - "8001:80"
    volumes:
      - ./backend:/var/www/html

  # 2. Dịch vụ Frontend (Chạy ở cổng 3000)
  frontend:
    build: ./frontend
    container_name: todo_frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html